[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
locker = "2r5VekMNiWPzi1pWwvJczrdPaZnJG59u91unSrTunwJg"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/andrewnguyen/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
