[workspace]
resolver = "2"
members = ["programs/*", "cli"]

[workspace.package]
edition = "2021"
version = "0.0.1"

[profile.release]
overflow-checks = true
lto = "fat"
codegen-units = 1

[profile.release.build-override]
opt-level = 3
incremental = false
codegen-units = 1

[workspace.dependencies]
anchor-lang = "0.28.0"
anchor-spl = "0.28.0"
anchor-client = "0.28.0"
clap = { version = "3.2.25", features = ["derive", "env"] }
csv = "1.3.0"
serde = "1.0.137"
solana-program = { version = "=1.16.16" }
solana-rpc-client = { version = "=1.16.16" }
solana-sdk = { version = "=1.16.16" }
spl-associated-token-account = "2.2.0"