name: Locker

on:
  pull_request:
    branches:
      - main
      - staging

env:
  SOLANA_CLI_VERSION: 1.18.21
  NODE_VERSION: 18.14.2
  ANCHOR_CLI_VERSION: 0.30.1

jobs:
  program_changed_files:
    runs-on: ubuntu-latest
    outputs:
      program: ${{steps.changed-files-specific.outputs.any_changed}}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Get specific changed files
        id: changed-files-specific
        uses: tj-actions/changed-files@v18.6
        with:
          files: |
            programs/locker

  locker_unit_test:
    runs-on: ubuntu-latest
    needs: program_changed_files
    if: needs.program_changed_files.outputs.program == 'true'
    steps:
      - uses: actions/checkout@v2
      # Install rust + toolchain
      - run: rustup toolchain install stable --component clippy
      # Cache rust, cargo
      - uses: Swatinem/rust-cache@v2
        with:
          prefix-key: "v1"
      - run: cargo test --package locker
        shell: bash

  locker_anchor_test:
    runs-on: ubuntu-latest
    needs: program_changed_files
    if: needs.program_changed_files.outputs.program == 'true'
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup-solana
      - uses: ./.github/actions/setup-dep
      - uses: ./.github/actions/setup-anchor
      # Install rust + toolchain
      - uses: dtolnay/rust-toolchain@1.76.0
      # Cache rust, cargo
      - uses: Swatinem/rust-cache@v2
        with:
          prefix-key: "v1"
      # Cache node_modules
      - uses: actions/cache@v2
        id: cache-node-modules
        with:
          path: ./node_modules
          key: ${{ runner.os }}-${{ hashFiles('./package-lock.json') }}
      - run: npm install
        shell: bash
      - run: sed -i -E 's/, *"cli"//g' Cargo.toml && rm -f Cargo.toml-E
      - run: anchor test -- --features localnet
        shell: bash
