name: Generate Anchor IDL
on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual triggering
jobs:
  generate-idl:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Ensures full history for commits
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
      - uses: metadaoproject/setup-anchor@v3.1
        with:
          anchor-version: "0.30.1"
          solana-cli-version: "2.1.15" # Set it to 2.x.x to use the Anza release
          node-version: "20.16.0"
      - run: anchor build
        # TODO: test rust caching
      - uses: Swatinem/rust-cache@v2
      - name: Move idl.json
        run: |
          mv target/idl/locker.json ./sdk/artifacts/
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          new_branch: idl
          default_author: github_actions
